# Generated by Django 6.1.1 on 2026-09-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('cloud', 'Cloud & DevOps'), ('data', 'Data & ML'), ('tools', 'Tools'), ('soft', 'Soft Skill'), ('other', 'Other')], default='other', max_length=20)),
                ('aliases', models.CharField(blank=True, help_text="Comma-separated alternate spellings, e.g. 'js, ecmascript'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('related', models.ManyToManyField(blank=True, help_text='Skills that partially transfer (e.g. MySQL <-> PostgreSQL)', to='jobs.skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry / Fresher'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='entry', max_length=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(blank=True, editable=False, null=True)),
                ('embedding_backend', models.CharField(blank=True, editable=False, max_length=40)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='jobs_job_is_acti_5b4a60_idx')],
            },
        ),
    ]
