# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import resumes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('summary', models.TextField(blank=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('unmapped_skills', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, editable=False, null=True)),
                ('embedding_backend', models.CharField(blank=True, editable=False, max_length=40)),
                ('skills', models.ManyToManyField(blank=True, related_name='resumes', to='jobs.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
